### PR TITLE
Entesb 17446 readme adoc

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Issue: https://issues.redhat.com/browse/ENTESB-17446

This fix changes documentation format from *.md to *.adoc.
I used pandoc tool for converting the content.
Here is the whole command
```
find . -name "README.md" | while read i; do pandoc  --markdown-headings=atx --verbose --wrap=preserve --toc --reference-links -t asciidoc "$i" -o "${i%.*}.adoc"; echo "$i"; done
```
I kept the change in 2 commits - renaming of the files and content change - to keep history of all changed files. 
Squashing it into 1 commit shows on github different comparisons which makes it hard to see, that content is unchanged.

(I suggest to look directly into commit with changed content to see correct diffs)

@tdiesler WDYT? The requirements doesn't need all README files from the project to be changed, but it makes sense to keep all of them in the same format. So I changed all of them/

### CODE REVIEW

**Comment by tdiesler** [comment]
Have you checked with Fintan Bolton (@fbolton our docs lead) - I believe he is consuming these docs?
If the change is fine with him, it is fine with me as well.

**Comment by briandooley** [comment]
@JiriOndrusek Fuse docs team agrees with this change.

**Comment by JiriOndrusek** [comment]
@tdiesler Fuse doc team agrees.

**Comment by JiriOndrusek** [comment]
Hi @tdiesler would it be possible to approve/merge this PR?

**Comment by tdiesler** [comment]
Again, have you checked with @fbolton?

**Comment by JiriOndrusek** [comment]
@tdiesler unfortunately fbolton left RH, @briandooley replaces him. So I asked him, see comments above.

**Comment by briandooley** [comment]
@tdiesler Fintan Bolton is not longer working in Red Hat and I have taken over some of his duties. I have run this by the team and they approve of this PR.

**Comment by tdiesler** [comment]
Great, then lets do it

**Pull request merged**
